parallel-jobs = 1
enable-module-update = true

[Music-Morphe-93353]
app-name = "YouTube Music Morphe 9.33.53"
patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "Morphe"

build-mode = "module"
arch = "arm64-v8a"
version = "9.33.53"

patcher-args = "--force"

direct-dlurl = "https://github.com/cybr47/revanced-magisk-module/releases/download/cherry/com.google.android.apps.youtube.music-9.33.53-arm64-v8a.apk"
