parallel-jobs = 1
remove-rv-integrations-checks = false

[Gboard-Advanced-Voice]
app-name = "Gboard Advanced Voice"
patches-source = "jasonwu1994/Gboard-patches"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "Gboard Patches"

build-mode = "apk"
arch = "arm64-v8a"
version = "18.0.3.954559732-release-arm64-v8a"

excluded-patches = "'Package Rename'"

direct-dlurl = "https://github.com/cybr47/revanced-magisk-module/releases/download/stock/com.google.android.inputmethod.latin_18.0.3.954559732-release-arm64-v8a-175940518_minAPI26.arm64-v8a.nodpi._apkmirror.com.apk"
